# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\接单\ElecDictionary/ui/editUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWidget(object):
    def setupUi(self, EditWidget):
        EditWidget.setObjectName("EditWidget")
        EditWidget.resize(370, 260)
        EditWidget.setStyleSheet("")
        self.okBtn = QtWidgets.QPushButton(EditWidget)
        self.okBtn.setGeometry(QtCore.QRect(48, 195, 104, 39))
        self.okBtn.setObjectName("okBtn")
        self.cancelBtn = QtWidgets.QPushButton(EditWidget)
        self.cancelBtn.setGeometry(QtCore.QRect(222, 195, 104, 39))
        self.cancelBtn.setObjectName("cancelBtn")
        self.editLabel = QtWidgets.QLabel(EditWidget)
        self.editLabel.setGeometry(QtCore.QRect(49, 20, 96, 32))
        self.editLabel.setObjectName("editLabel")
        self.cnEditLine = QtWidgets.QLineEdit(EditWidget)
        self.cnEditLine.setGeometry(QtCore.QRect(22, 131, 327, 44))
        self.cnEditLine.setObjectName("cnEditLine")
        self.label_3 = QtWidgets.QLabel(EditWidget)
        self.label_3.setGeometry(QtCore.QRect(11, 20, 28, 28))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/main/img/edit.png"))
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(EditWidget)
        self.widget.setGeometry(QtCore.QRect(0, 76, 370, 37))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.enEditLine = QtWidgets.QLineEdit(self.widget)
        self.enEditLine.setAlignment(QtCore.Qt.AlignCenter)
        self.enEditLine.setObjectName("enEditLine")
        self.horizontalLayout.addWidget(self.enEditLine)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(EditWidget)
        QtCore.QMetaObject.connectSlotsByName(EditWidget)

    def retranslateUi(self, EditWidget):
        _translate = QtCore.QCoreApplication.translate
        EditWidget.setWindowTitle(_translate("EditWidget", "Dialog"))
        self.okBtn.setText(_translate("EditWidget", "确认"))
        self.cancelBtn.setText(_translate("EditWidget", "取消"))
        self.editLabel.setText(_translate("EditWidget", "修改/增加"))
        self.enEditLine.setText(_translate("EditWidget", "Apple"))
from resource.qrc import ElecDict_rc
